### ISSUE TITLE
Data handler expects Location, Study to be required fields

### ISSUE THREAD

**Issue by jeancochrane** [datamade/just-spaces#163]
While we don't require a Survey to have a Location or Study in the Survey Create form, the data handler does in fact expect these attributes to exist, and will throw an error on survey submit if they don't:

https://github.com/datamade/just-spaces/blob/666a54eb4832fb53eea5839421117b537bfb6022/fobi_custom/plugins/form_handlers/collect_data/fobi_form_handlers.py#L30-L31

The error in question:

```
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by beamalsky** [comment]
Location and Study are now required in the Survey creation form, so we can close this issue. Should still make sure the data handler doesn't fail silently, as described in #164!
